---
name: build

on:
  pull_request:
  push:
    branches:
    - "!gh-pages"
    - "**"
    tags:
    - "v*"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: '${{ matrix.os.name }}-${{ matrix.os.version }}'
    strategy:
      fail-fast: false
      matrix:
        os:
        - {name: ubuntu, version: latest}
        - {name: macos, version: latest}
        python-version: [3.7, 3.8, 3.9, '3.10.9', '3.11.1']

    steps:
    - name: Grab source
      uses: actions/checkout@v3.1.0

    - name: Python Setup (${{ matrix.python-version }})
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Python Environment
      run: |
        python -m site --user-base
        echo "$(python -m site --user-base)/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        python -m pip install coverage black isort
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        ./toolbox/pkgs/${{ matrix.os.name }}.sh

    - name: Build
      run: |
        make all

    - name: Executable entry-points
      run: |
        yace --help
        python3 -m yace --help

    - name: Produce coverage report
      run: |
        make coverage
        mv htmlcov output/

    - name: Upload generated sources and doxygen
      uses: actions/upload-artifact@v3.1.1
      with:
        name: 'archive-${{ matrix.os.name }}-${{ matrix.os.version }}-py${{ matrix.python-version }}'
        path: output/*
        if-no-files-found: error

    - name: Publish Coveralls
      if: (startsWith(github.ref, 'refs/tags/v') && (matrix.os.name == 'ubuntu') && (matrix.python-version == '3.7'))
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov

    - name: Publish Package
      if: (startsWith(github.ref, 'refs/tags/v') && (matrix.os.name == 'ubuntu') && (matrix.python-version == '3.7'))
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python3 setup.py sdist bdist_wheel
        twine upload dist/*
